e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('NoBoneZ/', admin.site.urls),
    path("main_store/", include("main_store.urls")),
    path("", RedirectView.as_view(url="main_store/", permanent=True)),
    path("accounts/", include('nucleus.urls')),
    path("admin_overwatch/", include("admin_overwatch.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_store/urls.py
from django.urls import path

from . import views

app_name = "main_store"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/product_details/", views.product_details, name="product_details"),
    path("<int:pk>/product_details/make_report", views.make_report, name="make_report"),
    path("<int:pk>/add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("order_summary/", views.order_summary, name="order_summary"),
    path("<int:pk>/order_summary/<int:id>/remove_product", views.remove_from_cart, name="remove_from_cart"),
    path("<int:pk>/order_summary/<int:id>/reduce_quantity", views.reduce_quantity, name="reduce_quantity"),
    path("<int:pk>/order_summary/<int:id>/increase_quantity", views.increase_quantity, name="increase_quantity"),
    path("<int:pk>/save_product_wishlist/<int:id>", views.save_product, name="save_product"),
    path("<int:pk>/remove_product_wishlist/<int:id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("<int:pk>/check_out/", views.user_checkout, name="checkout"),

]

nucleus/urls.py
from django.urls import path

from . import views

app_name = "nucleus"

urlpatterns = [
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_in/", views.user_sign_in, name="sign_in"),
    path("sign_out/", views.user_sign_out, name="sign_out"),
    path("password_recovery/", views.recover_password, name="recover_password"),
    path("reset_password/password-token/<str:uid>/<str:token>", views.reset_password, name="reset_password"),

    path("profile/<int:pk>/", views.UserProfile.as_view(), name="profile"),
    path("profile/<int:pk>/update_details/", views.user_update_details, name="update_details"),
    path("profile/<int:pk>/change_password/", views.change_password, name="change_password"),
    path("profile/<int:pk>/close_account/", views.close_account, name="close_account"),
    path("profile/<int:pk>/wishlist/", views.user_wishlist, name="user_wishlist"),
    path("profile/<int:pk>/user_review/", views.user_review, name="user_review"),
    path("profile/<int:pk>/address_book/", views.UserAddress.as_view(), name="user_address"),
    path("profile/<int:pk>/inbox", views.UserInbox.as_view(), name="user_inbox"),
    path("profile/<int:pk>/my_orders", views.UserAllOrders.as_view(), name="user_all_orders"),
]

nucleus/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.validators import MinValueValidator, MaxValueValidator
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class InactiveManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_active=False)


class ActiveManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class StaffManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_staff=True)


class User(AbstractUser):
    first_name = models.CharField(max_length=30, null=True, blank=True)
    middle_name = models.CharField(max_length=30, blank=True, null=True)
    username = models.CharField(max_length=19, unique=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField(unique=True)
    profile_picture = models.ImageField(upload_to="user_profile_picture", default="avatar.svg")
    age = models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(16)], null=True, blank=True)
    phone_number = PhoneNumberField(unique=True, null=True, )
    is_vendor = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects = UserManager()
    active_objects = ActiveManager()
    inactive_objects = InactiveManager()
    staff_objects = StaffManager()


class Vendor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name_of_store = models.CharField(max_length=500, null=True)
    location_of_store = models.TextField()
    next_of_kin_name = models.CharField(max_length=200)
    next_of_kin_address = models.TextField()
    next_of_kin_phone_number = PhoneNumberField(unique=True)
    followers = models.ManyToManyField(User, related_name="vendor_followers")


class Inbox(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.CharField(null=True, max_length=70)
    inbox = models.TextField()
    date_sent = models.DateTimeField(auto_now_add=True)

nucleus/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from .models import User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        exclude = ("date_joined", "last_login", "superuser_status", "staff_status", "is_active", "password",
                   )


class MyUserEditForm(UserChangeForm):
    class Meta:
        model = User
        exclude = ("date_joined", "last_login", "superuser_status", "staff_status", "is_active", "password",
                   "email", "password1", "password2", "username"
                   )

nucleus/views.py
import math

from django.shortcuts import render, reverse
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate, update_session_auth_hash
from django.contrib.sites.shortcuts import get_current_site
from django.views.generic import DetailView, ListView
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, AccessMixin
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.conf import settings

from .forms import MyUserCreationForm, MyUserEditForm
from .models import User, Inbox
from main_store.models import WishList, Cart, Checkout, Product, OrderedProduct
from main_store.forms import FeedbackForm


# Create your views here.

class UserIsNotOwnerMixIn(UserPassesTestMixin):
    def dispatch(self, request, *args, **kwargs):
        if request.user.id == kwargs['pk']:
            return super().dispatch(request, *args, **kwargs)
        else:
            return self.handle_no_permission()


# def send_email_func(email_body: dict):
#     try:
#         html = render_to_string('accounts/mail_body.html', {"message:email_body['messages']})
#         subject = email_body["subject"]
#         email_from = settings.EMAIL_HOST_USER
#         recipient_list = email_body["recipients]
#
#         mail = EmailMessage(subject, email_body["messages"], to=[recipient_list])
#         mail.send()
#         return True
#
#     except Exception as e:
#         print(e)
#         return

def user_sign_in(request):
    email = request.POST.get("email")
    password = request.POST.get("password")
    page = "sign_in"

    if request.method == "POST":
        try:
            user = User.active_objects.get(email=email)

        except:
            messages.error(request, "Email does not exist, you should probably sign up or check your e-mail")
            return render(request, "nucleus/signin_signup.html", {"page": page})

        user = authenticate(email=email, password=password)

        if user is not None:
            login(request, user)

            address_cart = Cart.active_objects.filter(ip_address=request.META.get("REMOTE_ADDR")).first()
            selected_cart = Cart.active_objects.filter(user_id=user.id).first()
            # print(selected_cart.ordered_products.all())

            if address_cart is not None:
                if selected_cart is not None:
                    for good in address_cart.ordered_products.all():
                        for merch in selected_cart.ordered_products.all():
                            print(merch.product)
                            # if merch.product.id == good.product.id:
                            #     print(good.id)
                            #     print(merch.id)
                            #     merch.id, good.id = good.id, merch.id
                            #     merch.quantity += good.quantity
                            #     merch.save()
                            #     # good.is_moved = True
                            #     good.delete()


                        else:
                            good.user = User.active_objects.get(id=request.user.id)
                            # good.is_moved = True
                            good.save()
                            selected_cart.ordered_products.add(good)
                            selected_cart.save()



                else:
                    selected_cart = Cart.objects.create(user_id=request.user.id)
                    selected_cart.save()
                    for good in address_cart.ordered_products.all():
                        good.user = User.active_objects.get(id=request.user.id)
                        # good.is_moved = True
                        good.save()
                        selected_cart.ordered_products.add(good)
                        selected_cart.save()

                selected_cart.save()
                # address_cart.is_checked_out = True
                address_cart.delete()

            return HttpResponseRedirect(reverse("main_store:index"))
        messages.error(request, "Invalid login details")
        return render(request, "nucleus/signin_signup.html", {"page": page})

    elif request.method == "GET":
        return render(request, "nucleus/signin_signup.html", {"page": page})


def user_sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("main_store:index"))


def sign_up(request):
    form = MyUserCreationForm()
    page = "sign_up"

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST, )

        if form.is_valid():
            my_user = form.save(commit=False)
            my_user.is_active = True
            my_user.save()

            my_user = User.active_objects.get(email=request.POST.get("email"))
            login(request, my_user)
            return HttpResponseRedirect(reverse("main_store:index"))
        messages.error(request, 'An error occurred during details entry, please check ')

    context = {
        "form": form,
        "page": page
    }

    return render(request, "nucleus/signin_signup.html", context)


class UserProfile(LoginRequiredMixin, AccessMixin, DetailView):
    model = User
    template_name = "nucleus/profile.html"
    context_object_name = 'user'
    login_url = "nucleus:sign_in"


@login_required(login_url="nucleus:sign_in")
def user_update_details(request, pk):
    if request.user.id != pk:
        return HttpResponseForbidden()

    user = User.active_objects.get(id=pk)
    form = MyUserEditForm(instance=user)
    page = "user_update_details"

    if request.method == "POST":
        form = MyUserEditForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            form.save()

            messages.success(request, "Profile updated Successfully !")
            return HttpResponseRedirect(reverse('nucleus:profile', args=[user.id]))

        else:
            print(form.errors)
            messages.error(request, 'Invalid detail entered')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    elif request.method == "GET":
        context = {
            "form": form,
            "page": page,
        }
        return render(request, "nucleus/profile_forms.html", context)


@login_required(login_url="nucleus:sign_in")
def change_password(request, pk):
    if request.user.id != pk:
        return HttpResponseForbidden()

    form = PasswordChangeForm(request.user)
    page = "change_password"

    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Password Changed Successfully")
            return HttpResponseRedirect(reverse("nucleus:profile", args=[pk]))
        else:
            messages.error(request, "please correct the error below")

    context = {"form": form,
               "page": page,
               }
    return render(request, "nucleus/profile_forms.html", context)


def close_account(request, pk):
    user = User.active_objects.get(id=pk)
    page = "close_account"

    if request.method == "POST":
        user.is_active = False
        user.save()

        logout(request)
        messages.success(request, "Account deleted Successfully")
        return HttpResponseRedirect(reverse("main_store:index"))

    context = {
        "page": page,
    }
    return render(request, "nucleus/profile_forms.html", context)


class UserWishlist(ListView):
    model = WishList
    template_name = "nucleus/profile_list.html"

    def get_queryset(self, **kwargs):
        selected_wishlist = WishList.objects.get(user_id=self.kwargs["pk"])
        return selected_wishlist.saved_products.all()

    def get_context_data(self, **kwargs):
        context = super(UserWishlist, self).get_context_data(**kwargs)
        context["wishlist"] = self.get_queryset()
        context["page"] = "wish_list"
        return context


@login_required(login_url="nucleus:sign_in")
def user_wishlist(request, pk):
    if request.user.id != pk:
        return HttpResponseForbidden()

    try:
        selected_wishlist = WishList.objects.get(user_id=pk)
    except Exception as e:
        messages.info(request, "Empty Wishlist")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    wishlist = selected_wishlist.saved_products.all()
    page = "wishlist"

    context = {
        "wishlist": wishlist,
        "page": page
    }
    return render(request, "nucleus/profile_list.html", context)


@login_required(login_url="nucleus:sign_in")
def user_review(request, pk):
    if request.user.id != pk:
        return HttpResponseForbidden()

    products = []
    selected_carts = Cart.inactive_objects.filter(user_id=pk)
    for carts in selected_carts:
        for goods in carts.ordered_products.all():
            if not goods.is_reviewed:
                products.append(goods)

    page = "rate_review"
    form = FeedbackForm()

    if request.method == "POST":
        form = FeedbackForm(request.POST)

        if form.is_valid():
            user = User.active_objects.get(id=pk)
            product = Product.active_objects.get(id=request.POST.get("product"))
            print(user.id)
            print(product.id)
            reviewed_product = OrderedProduct.inactive_objects.filter(user_id=user.id, product_id=product.id).first()
            reviewed_product.is_reviewed = True
            reviewed_product.save()

            feed = form.save(commit=False)
            feed.user = User.active_objects.get(id=pk)
            print(feed.user)

templates/nucleus/profile.html
{% extends 'base.html' %}

{% block title %}<title>{{request.user.username | title}}'s profile</title>{% endblock %}
{% block content %}
<style>

    .account_info{
        margin:40px 0px 0px 50px;
    }
    .account_info li{
        list-style-type:none;
        padding:10px;
    }


    .account_info h2{
        margin:30px 30px 10px 10px;
    }

    .account_info p{
        margin:30px 30px 10px 10px;
        font-size:20px;
        font-family: 'Brush Script MT', cursive;
    }

    .account_info a{
        text-decoration:none;
        color:midnightblue;
    }

    .inner_info{
     border-radius:10px;
     margin:0px 400px 50px 400px;
     padding-left:200px;
     background-color:lightgray;

    }

    .inner_info img{
        width:150px;
        height:150px;
        margin-top:10px;
        margin-left:40px;
        margin-bottom:10px;
        border-radius:90px;
    }

</style>

<div class="account_info">
    <div class="inner_info">

        <img src="{{user.profile_picture.url}}" alt="{{user.username}}">
      <p>Welcome, {{user.username}}</p>
      <p>{{user.email}}</p>
        <br>
        <br>


           <h2>My Vilgax Account</h2>
      <ul>
         <a href="{% url 'nucleus:user_all_orders' user.id%}"><li>Orders</li></a>
         <a href="{% url 'nucleus:user_inbox' user.id %}"><li>Inbox</li></a>
         <a href="{% url 'nucleus:user_review' user.id %}"><li>Pending reviews</li></a>
         <a href="{% url 'nucleus:user_wishlist' user.id %}"><li>WishList</li></a>
          <a href=""><li>Recently Viewed</li></a>
      </ul>

      


      <h2>My Settings</h2>
      <ul>
         <a href="{% url 'nucleus:update_details' user.id %}"><li>Details</li></a>
         <a href="{% url 'nucleus:user_address' user.id %}"><li>Address Book</li></a>
         <a href="{% url 'nucleus:change_password' user.id %}"><li>Change Password</li></a>
         <a href="{% url 'nucleus:close_account' user.id %}"><li>Close Account</li></a>
      </ul>
    </div>

</div>
{% endblock %}

templates/nucleus/profile_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>{{page | title}} page</title>{% endblock %}
{% block content %}
<style>
  .profile_list{
    display:flex;
    align-items:center;
    justify-content:center;
    border-radius:9px;
    margin:50px 400px;
    background-color:whitesmoke;
    padding-bottom:50px;
  }


  .address_header img {
        width:20px;
        height:20px;
        margin-left: -130px;
        margin-top : -100px;
  }

  .address_header h2 {
        margin:20px 0px -20px 120px;
  }


   .address_body{
        margin-top:20px 0px 50px 0px;
   }

   .address_body table{
        border-collapse:collapse;
        width:75%;
        margin-top:20px;
        margin-left:40px;
        border:1px solid;
    }

   .address_body td{
        text-align:center;
    }

    .address_body th{
        background-color:grey;
        color:white;
    }

    .address_body th, td{
        padding:15px;
    }

    .total_price{
        margin-left:350px;
        margin-bottom:20px;
    }

    .c_orders_body img{
        margin-top:40px;
    }

   .c_orders_header img {
        width:20px;
        height:20px;
        margin-left: -80px;
        margin-top : -20px;
  }

  .c_orders_header h2 {
        margin-top :10px;
        margin-bottom : -20px;
  }

  .wishlist_header img {
        width:30px;
        height:30px;
        margin-left: 10px;
        margin-top : -90px;
  }

  .wishlist_header h2 {
        margin-top :100px;
        margin-bottom : -20px;
        margin-left: 180px;
  }

  .wish_img {
        width:100px;
        height:100px;
        margin-top:10px;
  }

  .ind_item_in_wish{
        border:1px solid black;
        padding: 20px;
        margin-top:40px;
  }

  .ind_item_in_wish button{
        border:1px solid black;
        cursor:pointer;
  }

  .w_add_2_cart{
        margin-right: 80px;
        padding:10px;
        margin-left:20px;

  }

  .w_remove_from_w{
        margin-right:80px;
        padding:10px;
        margin-top: -5px;
  }


  .inbox_list p{
    margin:10px 0px 0px -80px;
  }

   .inbox_list{
    margin-bottom:90px;
   }

</style>



<div class="profile_list">
  {% if page == 'address' %}
    <div class="address">

        <div class="address_header">
                    <h2>ADDRESS</h2>

                    <a href="{{request.META.HTTP_REFERER}}">
                        <img src="{% static 'images/arrow-left.svg' %}" alt="Go Back">
                    </a>
                </div>

        <div class="address_body">
            <table>
                <tr>
                    <th>S/N</th>
                    <th>Full Name</th>
                    <th>Address</th>
                    <th>Phone Number</th>
                </tr>

                {% for address in addresses %}
                <tr>
                    <td class="1-address">{{forloop.counter}}</td>
                    <td class="2-address">{{address.full_name}}</td>
                    <td class="3-address">{{address.address}}</td>
                    <td class="4-address">{{address.phone_number}}</td>
                    {% empty %}
                    <td class="3-address">No Registered Address Yet</td>
                </tr>
                {% endfor %}
            </table>

        </div>
    </div>
    {% endif %}

    {% if page == 'inbox' %}
    <div class="inbox_list">
        <h2>Inbox</h2>

        {% for message in messages  %}
        <h4>{{message.topic}}</h4>

        <p>{{message.inbox}}</p>

        <strong>{{message.date_sent | timesince}}</strong>
        {% empty %}
        <p>No Messages From Vilgax Stores Yet</p>
        {% endfor %}

    </div>
    {% endif %}

    {% if page == "orders" %}
    <div class="orders">

                <div class="c_orders_header">
                    <h2>ALL {{request.user.username | upper}}'s COMPLETED ORDERS</h2>

                    <a href="{{request.META.HTTP_REFERER}}">
                        <img src="{% static 'images/arrow-left.svg' %}" alt="Go Back">
                    </a>
                </div>


            <div class="c_orders_body">
                {% for good in bought_goods %}
                    <img src="{{good.product.picture_of_product_1.url}}" alt="{{good.product.name}}" width="100px">

                    <p>{{good.product.name | title}}</p>
                    <span>{{good.date_checked_out}}</span>
                    <p class="total_price">TOTAL PRICE: {{good.individual_product_price}}</p>

                    {% empty %}
                    <p>No Good Purchased as of this moment</p>
                {% endfor %}
                <br>
                <br>
                <br>

                <h3>Total amount spent in Vilgax stores : {{amount_spent}}</h3>
            </div>
    </div>
    {% endif %}

    {% if page == "wishlist" %}
    <div class=wishlist">
            <div class="wishlist_header">
                <h2>{{request.user.username | upper}}'s Wishlist</h2>

                <a href="{{request.META.HTTP_REFERER}}">
                    <img src="{% static 'images/arrow-left.svg' %}" alt="Go Back">
                </a>
            </div>

               <div class="wish_pack">
                  {% for product in wishlist %}
                    <div class="ind_item_in_wish">
                        <img src="{{product.picture_of_product_1.url}}" alt="{{product}}" class="wish_img">

                        <p>{{product.name}}</p>
                        {% if product.discount > 0 %}
                          <del>{{product.price}}</del>
                          <small>{{product.get_price_discount_percentage}}</small>
                        {% endif %}
                          <strong>#{{product.get_real_price}}</strong>


                          <a href="{% url 'main_store:add_to_cart' product.id %}">
                          <button type="button" class="w_add_2_cart">Add To Cart</button>
                          </a>

                          <a href="{% url 'main_store:remove_from_wishlist' request.user.id product.id %}">
                          <button type="button" class="w_remove_from_w">Remove From Wishlist</button>
                          </a>
                    </div>
                  {% empty %}
                  <p>No Product In the {{request.user.username}}'s wishlist</p>
                  {% endfor %}
               </div>
    </div>
        {% endif %}
</div>

{% endblock %}

templates/nucleus/signin_signup.html
{% extends "base.html" %}

{% block title %}<title>{{page}} page</title>{% endblock %}
{% block content %}
<style>
  .signin_sign_up{
        display:flex;
        align-items:center;
        justify-content:center;
        border-radius:9px;
        margin:50px 400px;
        background-color:whitesmoke;
    }

    .sign_up{
        margin-top:30px;
        margin-bottom:10px;
     }

     .signin{
        margin-top:30px;
        margin-bottom:10px;
     }

     .recover_password{
        margin-top:30px;
        margin-bottom:10px;
     }

     .reset_password{
        margin-top:30px;
        margin-bottom:10px;
     }

</style>



<div class="signin_sign_up">

    {% if page == "sign_in" %}
        <div class="signin">
            <form method="post" enctype="multipart/form-data" action="">
              {% csrf_token %}
              <label>Email: </label>
              <input type="text" name="email" placeholder="Enter your registered e-mail">
                <br>
                <br>

              <label>Password: </label>
              <input type="password" name="password">
                <br>
                <br>

              <input type="submit" value="Log In">
                <br>
                <br>

            </form>
              <p>You don't have an account ? <a href="{% url 'nucleus:sign_up' %}">Sign Up</a></p>
                <br>

                <a href="{% url 'nucleus:recover_password' %}"><p>Forgot password ? </p></a>
                <br>
                <br>
          </div>
    {% endif %}


    {% if page == "sign_up" %}
        <div class="sign_up">
                <form method="post" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                {{form.errors}}
                    <br>

                  <label>Email: </label>
                  {{form.email}}
                   <br>
                    <br>

                    <label>Username: </label>
                    {{form.username}}
                    <br>
                    <br>

                    <label>Phone number: </label>
                  {{form.phone_number}}
                   <br>
                  <br>

                  <label>Password </label>
                  {{form.password1}}
                   <br>
                  <br>

                    <label>Password Confirmation: </label>

                  {{form.password2}}
                   <br>
                  <br>

                    <input type="checkbox" required><span>I have read the <a href="" target="_blank">terms and condition</a>
                    and I agree to it. </span>
                   <br>
                  <br>

                    <input type="submit" value="Sign up">
                </form>
                <br>
                <p>Already have an account ? <a href="{% url 'nucleus:sign_in' %}">Sign in </a></p>

            </div>
    {% endif %}

    {% if page == 'recover_password' %}
        <div class="reset_password">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label>Kindly enter Your registered Email:</label>
            <input type="email" name="email" required>

            <button type="submit">Reset Password</button>

        </form>
    </div>
    {% endif %}


    {% if page == 'reset_password' %}
        <div class="reset_password_change">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Kindly enter Your New Password:</label>
                <input type="password" name="password1" required>

                <label>Kindly enter Your registered Email:</label>
                <input type="password" name="password2" required>

                <button type="submit">Change Password</button>

            </form>
        </div>
    {% endif %}







</div>
{% endblock %}