admin_overwatch/urls.py
from django.urls import path

from. import views


app_name = "admin_overwatch"

urlpatterns = [
    path("", views.index, name="index"),
    path("overwatch_signin/", views.overwatch_signin, name="overwatch_signin"),
    path("overwatch_signout/", views.overwatch_signout, name="overwatch_signout"),

    path("create_category/", views.create_category, name="overwatch_create_category"),
    path("create_sub_category/", views.create_sub_category, name="overwatch_create_sub_category"),

    path("create_product/", views.create_product, name='overwatch_create_product'),
    path("edit_product/<int:pk>/", views.edit_product, name="overwatch_edit_product"),
    path("delete_product/<int:pk>/", views.delete_product, name="overwatch_delete_product"),
    path("view_deleted_products/", views.DeletedProducts.as_view(), name="overwatch_view_deleted_products"),
    path("product_details/<int:pk>/", views.overwatch_product_details, name="overwatch_product_details"),
    path("global_sales/", views.global_sales, name="overwatch_global_sales")


]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('NoBoneZ/', admin.site.urls),
    path("main_store/", include("main_store.urls")),
    path("", RedirectView.as_view(url="main_store/", permanent=True)),
    path("accounts/", include('nucleus.urls')),
    path("admin_overwatch/", include("admin_overwatch.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_store/urls.py
from django.urls import path

from . import views

app_name = "main_store"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/product_details/", views.product_details, name="product_details"),
    path("<int:pk>/product_details/make_report", views.make_report, name="make_report"),
    path("<int:pk>/add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("order_summary/", views.order_summary, name="order_summary"),
    path("<int:pk>/order_summary/<int:id>/remove_product", views.remove_from_cart, name="remove_from_cart"),
    path("<int:pk>/order_summary/<int:id>/reduce_quantity", views.reduce_quantity, name="reduce_quantity"),
    path("<int:pk>/order_summary/<int:id>/increase_quantity", views.increase_quantity, name="increase_quantity"),
    path("<int:pk>/save_product_wishlist/<int:id>", views.save_product, name="save_product"),
    path("<int:pk>/remove_product_wishlist/<int:id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("<int:pk>/check_out/", views.user_checkout, name="checkout"),

]

nucleus/urls.py
from django.urls import path

from . import views

app_name = "nucleus"

urlpatterns = [
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_in/", views.user_sign_in, name="sign_in"),
    path("sign_out/", views.user_sign_out, name="sign_out"),
    path("password_recovery/", views.recover_password, name="recover_password"),
    path("reset_password/password-token/<str:uid>/<str:token>", views.reset_password, name="reset_password"),

    path("profile/<int:pk>/", views.UserProfile.as_view(), name="profile"),
    path("profile/<int:pk>/update_details/", views.user_update_details, name="update_details"),
    path("profile/<int:pk>/change_password/", views.change_password, name="change_password"),
    path("profile/<int:pk>/close_account/", views.close_account, name="close_account"),
    path("profile/<int:pk>/wishlist/", views.user_wishlist, name="user_wishlist"),
    path("profile/<int:pk>/user_review/", views.user_review, name="user_review"),
    path("profile/<int:pk>/address_book/", views.UserAddress.as_view(), name="user_address"),
    path("profile/<int:pk>/inbox", views.UserInbox.as_view(), name="user_inbox"),
    path("profile/<int:pk>/my_orders", views.UserAllOrders.as_view(), name="user_all_orders"),
]

admin_overwatch/models.py
from django.db import models

# Create your models here.

admin_overwatch/forms.py
from django import forms

from main_store.models import Category, Labels, Product, Feedback, SubCategory


class CategoryEditForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("is_active",)


class LabelEditForm(forms.ModelForm):
    class Meta:
        model = Labels
        fields = "__all__"


class SubcategoryEditForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = "__all__"

admin_overwatch/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.views.generic import ListView

from nucleus.models import User, Vendor
from main_store.models import Category, SubCategory, Labels, Product, OrderedProduct, Cart, Report, Feedback
from .forms import ProductEditForm, CategoryEditForm, SubcategoryEditForm


# Create your views here.

@login_required(login_url="admin_overwatch:overwatch_signin")
def index(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    sales = []
    categories = Category.objects.all()

    search = request.GET.get("search") if request.GET.get("search") is not None else ""

    products = Product.active_objects.filter(
        Q(name__icontains=search) | Q(sub_category__category__name__icontains=search)
        # | Q(vendor__name_of_store=search) | Q(sub_category__icontains=search)
    )

    checked_out_carts = Cart.inactive_objects.all()

    for carts in checked_out_carts:
        for goods in carts.ordered_products.all():
            sales.append(goods)

    context = {
        "categories": categories,
        "products": products,
        "sales": sales,
    }

    return render(request, "admin_overwatch/overwatch_index.html", context)


def overwatch_signin(request):
    if request.user.is_authenticated:
        logout(request)

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        # try:
        #     user = User.staff_objects.get(email=email)
        # except ObjectDoesNotExist:
        #     pass

        user = authenticate(email=email, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("admin_overwatch:index"))
        messages.error(request, "Invalid details")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    context = {
        "page": "sign_in",

    }
    return render(request, "admin_overwatch/overwatch_forms.html", context)


def overwatch_signout(request):
    logout(request)
    return HttpResponseRedirect(reverse("main_store:index"))


@login_required(login_url="admin_overwatch:overwatch_signin")
def overwatch_product_details(request, pk):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    product_sales = []
    total_quantity = 0
    total_sold = 0
    product = Product.active_objects.get(id=pk)
    sold_carts = Cart.inactive_objects.all()

    for carts in sold_carts:
        for goods in carts.ordered_products.all():
            if goods.product.id == pk:
                product_sales.append(goods)
                total_quantity += goods.quantity
                total_sold += goods.individual_product_price()
    context = {
        "product": product,
        "product_sales": product_sales,
        "total_quantity": total_quantity,
        "total_sold": total_sold
    }

    return render(request, "admin_overwatch/overwatch_product_detail.html", context)


@login_required(login_url="admin_overwatch:overwatch_signin")
def edit_product(request, pk):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    product = get_object_or_404(Product, id=pk)
    form = ProductEditForm(instance=product)
    page = "create_edit"

    if request.method == "POST":
        form = ProductEditForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()

            messages.success(request, f"{product.name} edited successfully")
            return HttpResponseRedirect(reverse("admin_overwatch:overwatch_product_details", args=[pk]))
        messages.error(request, "invalid entry, kindly check the entry")

    context = {
        "form": form,
        "page": page
    }

    return render(request, "admin_overwatch/overwatch_forms.html", context)


@login_required(login_url="admin_overwatch:overwatch_signin")
def create_product(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    form = ProductEditForm()
    page = "create_edit"

    if request.method == "POST":
        form = ProductEditForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

            messages.success(request, f"Product created successfully")
            return HttpResponseRedirect(reverse("admin_overwatch:index"))
        messages.error(request, "Invalid Entry, Kindly check your form")
    context = {
        "form": form,
        "page": page
    }

    return render(request, "admin_overwatch/overwatch_forms.html", context)


@login_required(login_url="admin_overwatch:overwatch_signin")
def delete_product(request, pk):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    product = Product.objects.get(id=pk)
    product.is_active = not product.is_active
    product.save()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="admin_overwatch:overwatch_signin")
def create_category(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    page = "create_edit"
    form = CategoryEditForm()

    if request.method == "POST":
        form = CategoryEditForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

            messages.success(request, "Category created successfully")
            return HttpResponseRedirect(reverse("admin_overwatch:index"))
        messages.error(request, "Error!! kindly check your Input")

    context = {
        "page": page,
        "form": form,
    }
    return render(request, "admin_overwatch/overwatch_forms.html", context)


@login_required(login_url="admin_overwatch:overwatch_signin")
def create_sub_category(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    page = "create_edit"
    form = SubcategoryEditForm()

    if request.method == "POST":
        form = SubcategoryEditForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

            messages.success(request, "Category created successfully")
            return HttpResponseRedirect(reverse("admin_overwatch:index"))
        messages.error(request, "Error!! kindly check your Input")

    context = {
        "page": page,
        "form": form,
    }
    return render(request, "admin_overwatch/overwatch_forms.html", context)


class DeletedProducts(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Product
    template_name = "admin_overwatch/overwatch_deleted_products.html"
    login_url = "admin_overwatch:overwatch_signin"

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        return Product.inactive_objects.all

    def get_context_data(self, *args, **kwargs):
        context = super(DeletedProducts, self).get_context_data(**kwargs)
        context["products"] = self.get_queryset()
        return context


@login_required(login_url="admin_overwatch:overwatch_signin")
def global_sales(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()

    sold_products = []
    total_quantity = 0
    total_amount = 0
    selected_carts = Cart.inactive_objects.all()
    for carts in selected_carts:
        for goods in carts.ordered_products.all():
            sold_products.append(goods)
            total_quantity += goods.quantity
            total_amount += goods.individual_product_price()

    context = {
        "sold_products": sold_products,
        "total_quantity": total_quantity,
        "total_amount": total_amount,
    }

    return render(request, "admin_overwatch/overwatch_global_sales.html", context)

templates/admin_overwatch/overwatch_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Title</title>{% endblock %}
</head>
<body>
    {% include "admin_overwatch/overwatch_navbar.html" %}

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}
    {% endblock %}

</body>
</html>

templates/admin_overwatch/overwatch_deleted_products.html
{% extends "admin_overwatch/overwatch_base.html" %}

{% load static %}
{% block title %}<title>Deleted Products</title>{% endblock %}
{% block content %}
<style>
    .overwatch_deleted_products{

    }



    .deleted_products{


    }

    .individual_deleted_products{
        border:1px solid black;
        margin:50px 1300px 50px 90px;
        padding:20px;
    }

    .product_image{
        width:80px;
        height:80px;
    }

    .delete_logo img{
       width:30px;
        height:30px;
    }


</style>
<div class="overwatch_deleted_products">
    <div class="deleted_products">
        <h2>Deleted products</h2>
        <p>{{products.count}} products deleted</p>
        {% for product in products %}
            <div class="individual_deleted_products">
                 <img src="{{product.picture_of_product_1.url}}" alt="{{product.name}}" class="product_image">
                          <h4>{{product.name}}</h4>
                          <p>{{product.price}}</p>


                        <div class="delete_logo">
                            <a href="{% url 'admin_overwatch:overwatch_delete_product' product.id %}"><img src="{% static 'images/restore.png' %}" alt="un_delete_product" class=""></a>
                        </div>
            </div>
        {% empty %}
            <p>No Deleted products</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/admin_overwatch/overwatch_forms.html
{% extends "admin_overwatch/overwatch_base.html" %}
{% load crispy_forms_tags %}


{% block title %}<title>{{page}}'s page</title>{% endblock %}
{% block content %}
<style>
    .overwatch_forms{
        display:flex;
        align-items:center;
        justify-content:center;
        margin:300px;
    }

</style>

<div class="overwatch_forms">
    {% if page == "sign_in" %}
    <div class="sign_in_form">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Email: </label>
                <input type="email" name="email" placeholder="Enter Admin Enabled E-mail">
                <br>
                <br>

                <label>Password: </label>
                <input type="password" name="password">
                <br>
                <br>

                <input type="submit" value="sign in">

            </form>
    </div>
    {% endif %}

    {% if page == "create_edit" %}
    <div class="create_edit_form">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_table}}

            <input type="submit" value="Submit">
        </form>

    </div>
    {% endif %}



</div>
{% endblock %}

templates/admin_overwatch/overwatch_global_sales.html
{% extends "admin_overwatch/overwatch_base.html" %}

{% block title %}<title>Global Sales</title>{% endblock %}
{% block content %}
<style>
  .global_sales table{
        border-collapse:collapse;
        width:75%;
        margin-top:20px;
        margin-left:40px;
        border:1px solid;
    }

   .global_sales td{
        text-align:center;
    }

    .global_sales th{
        background-color:grey;
        color:white;
    }

    .global_sales th, td{
        padding:15px;
    }

</style>


<div class="global_sales">
  <table>
    <h3>Vilgax's Store Global Sales </h3>
    <tr>
      <th>S/N</th>
      <th>Date of purchase</th>
      <th>product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Customer</th>
      <th>Net price</th>
    </tr>

      {% for product in sold_products %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{product.date_checked_out}}</td>
      <td>{{product.product.name}}</td>
      <td>{{product.product.get_real_price}}</td>
      <td>{{product.quantity}}</td>
      <td>{{product.user}}</td>
      <td>{{product.individual_product_price}}</td>
    </tr>

    {% empty %}
    <tr><td colspan="7"><h2>No Sales Made Yet</h2></td></tr>
    {% endfor %}

    <tr>
      <td colspan="3">Total Quantity Sold</td>
      <td colspan="3">{{total_quantity}}</td>
    </tr>

    <tr>
      <td colspan="3">Total Amount Generated</td>
      <td colspan="3">#{{total_amount}}</td>
    </tr>

  </table>
</div>
{% endblock %}

templates/admin_overwatch/overwatch_index.html
{% extends "admin_overwatch/overwatch_base.html" %}
{% load static %}

{% block title %}<title>Vilgax Admin</title>{% endblock %}
{% block content %}
<style>
  .main_store_home{
    display:grid;
    grid-template-columns:1fr 3fr 1fr;
  }

  .main_store_categories a{
    text-decoration:none;
    color:black;
  }

  .main_store_categories li{
    list-style-type:none;
  }

  .products_list{
    display: grid;
    width: 100%;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: auto;
    row-gap: 30px;
    column-gap: 30px;
  }

  .product{
    border:1px solid black;
    padding-right:-30000px;
  }

  .product_image{
    width:70px;
    height:70px;
  }

  .cart_logo img{
    width:50px;
    float:right;
    padding:10px;
  }

  .like_product{
    width:40px;
  }

  .sales_activity{
    border:1px solid black;
    margin-left:15px;
    margin-right:20px;
    border-radius:5px;
    margin-top:20px;
  }

   .sales_activity img{
    width:70px;
    padding:5px;
  }

  .sales_activity span{
       border:1px solid black;
       border-radius:3px;
       background-color:black;
       color:white;
       float:right;

  }

  .sales_activity p{
        padding:8px;

  }

  .recent_sales h2{
    margin:10px 10px 10px 15px;
  }

   .view_product{
        width:40px;
     }

    .create_room{
        float:right;
        margin-bottom:20px;
        cursor:pointer;
    }


  .edit_logo img{
        width:20px;
  }

  .delete_logo img{
        max-width:20px;
        display:block;
  }

  .create_category button{
        float:right;
  }

  .create_sub_category button{
        float:right;
        margin-right:10px;
  }


  .create_sub_category a{
        cursor:pointer;
  }

  .main_store_products{
        margin-left:20px;
        margin-right:20px;
  }

  .view_deleted_products{
        margin-top:5px;
  }

  .view_global_sales button{
        margin-left:20px;

  }

</style>


<div class="main_store_home">

  <div class="main_store_categories">
    <h3>Categories</h3>

        <div class="create_category">
          <a href="{% url 'admin_overwatch:overwatch_create_category' %}">
            <button type="button">Create Category</button>
          </a>
        </div>
      <ul>
          <a href="{% url 'main_store:index' %}"><li>All</li></a>
        {% for category in categories %}
        <a href="{% url 'admin_overwatch:index' %}?search={{category.name}} "><li>{{category}}</li></a>
        {% empty %}
        <p>No categories Available</p>
        {% endfor %}
      </ul>


  </div>

  <div class="main_store_products">
        <h2>products Available</h2>
        <p>{{products.count}} Available

            <div class="create_room">
                <a href="{% url 'admin_overwatch:overwatch_create_product' %}">
                <button type="button">Create product</button>
                </a>
            </div>


             <div class="create_sub_category">
                <a href="{% url 'admin_overwatch:overwatch_create_sub_category' %}">
                <button type="button">Create SubCategory</button>
                </a>
            </div>


             <div class="view_deleted_products">
                <a href="{% url 'admin_overwatch:overwatch_view_deleted_products' %}">
                <button type="button">View Deleted products</button>
                </a>
            </div>

          <div class="products_list">
            {% for product in products %}

            <div class="product">
                  <img src="{{product.picture_of_product_1.url}}" alt="{{product.name}}" class="product_image">
                  <h4>{{product.name}}</h4>
                  <p>{{product.price}}</p>

                 <div class="edit_logo">
                    <a href="{% url 'admin_overwatch:overwatch_product_details' product.id %}"><img src="{% static 'images/edit.svg' %}" alt="edit_product" class=""></a>
                </div>

                <div class="delete_logo">
                    <a href="{% url 'admin_overwatch:overwatch_delete_product' product.id %}"><img src="{% static 'images/trash.svg' %}" alt="delete_product" class=""></a>
                </div>




            </div>

            {% empty %}
            <p>No products Available</p>
            {% endfor %}

        </div>

    </div>

  <div class="recent_sales">
    <h2>Recent Sales </h2>

      <div class="view_global_sales">
                <a href="{% url 'admin_overwatch:overwatch_global_sales' %}">
                <button type="button">View Global Sales</button>
                </a>
            </div>

      {% for sale in sales %}
      <div class="sales_activity">
          <img src="{{sale.user.profile_picture.url}}" alt="{{sale.user.username}}">
          <p>{{sale.user.username}} purchased {{sale.quantity}}X of {{sale.product.name}} for
              #{{sale.individual_product_price}} from <strong>{{sale.product.vendor.user.username}}</strong></p>
          <hr>

          <a href="{% url 'admin_overwatch:index'%}?search={{sale.product.get_category}}">
            <span>{{sale.product.get_category}}</span>
          </a>


        <br>
          <br>
      </div>
      <br>
      {% empty %}
      <p>No Sales Yet</p>
      {% endfor %}
  </div>

</div>
{% endblock %}

templates/admin_overwatch/overwatch_navbar.html
{% load static %}
<style>
    *{
        margin: 0;
        box-sizing: border-box;
    }


    .nav_bar{
        display: flex;
        justify-content: space-between;
        padding: 2px;
        background-color: ghostwhite;
        position: sticky;
        top: 0;
    }

    .logo{
        display: flex;
        justify-content: space-evenly;
        text-decoration:none;
        color:black;
    }

    .logo img{
        width: 70px;
        height: 70px;
    }

    .logo_text{
        margin-top: 20px;
        font-size: 20px;
        font-family: 'Brush Script MT', cursive;
    }

    .main_search_bar{
        width: 300px;
        height: 40px;
        border-radius:10px;
        margin-left:-380px;
        margin-top:20px;
    }


    .logout{
        width:30px;

    }

</style>

<div class="nav_bar">

    <a class="logo" href="{% url 'admin_overwatch:index' %}">
        <img src="{% static 'images/vilgax.png' %}" alt="My_logo" class="logo" >
        <p class="logo_text">Vilgax Stores (ADMIN)</p>
    </a>

    <form>
    <input class="main_search_bar" type="text" name="search" placeholder="Enter Product name, vendor, category">
    </form>



<!--            <a class="logout" href="{% url 'admin_overwatch:overwatch_signout' %}">-->
<!--                <img src="{% static 'images/switch.png' %}"alt="My_logo" class="logout">-->
<!--            </a>-->


</div>

templates/admin_overwatch/overwatch_product_detail.html
{% extends 'admin_overwatch/overwatch_base.html' %}
{% load static %}

{% block title %}<title>{{product.name}}'s page</title>{% endblock %}
{% block content %}
<style>
    .whole_product_details_page{
        display:grid;
        grid-template-columns:3fr 2fr;
        color:blue;
    }



    .mainly_product_details img{
         width:50px;

    }

    .mainly_product_details{
         margin-left:150px;
         margin-right:50px;

    }

    .intro_details{
         border:1px solid black;
         margin:50px 50px 10px 150px;

    }

    .intro_details img{
         width:250px;

    }


     .product_details{
         border:1px solid black;
         margin:0px 50px 10px 150px;

    }

     .product_specification{
         border:1px solid black;
         margin:0px 50px 10px 150px;
         display:grid;
         grid-template-columns:1fr 1fr;

    }

     .customer_feedback{
         border:1px solid black;
         margin:0px 50px 10px 150px;

    }

    .product_detail_add_to_cart{
        margin:0px 50px 0px 200px;
        cursor:pointer;
    }

    .product_detail_add_to_cart button{
        margin:0px 50px 0px 200px;
        cursor:pointer;
    }

    .product_sales_info table{
        border-collapse:collapse;
        width:75%;
        margin-top:20px;
        margin-left:40px;
        border:1px solid;
    }

   .product_sales_info td{
        text-align:center;
    }

    .product_sales_info th{
        background-color:grey;
        color:white;
    }

    .product_sales_info th, td{
        padding:15px;
    }


</style>



<div class="whole_product_details_page">


    <div class="mainly_product_details">

        <a href="{% url 'admin_overwatch:overwatch_edit_product' product.id %}">
        <button type="button">Edit product</button>
        </a>


        <div class="intro_details">

            <img src="{{product.picture_of_product_1.url}}" alt="{{product.name}}">
            <h3>{{product.name}}</h3>

            {% if product.discount > 1%}
                <span>{{product.get_price_discount_percentage}}</span>
                <del>{{product.get_price}}</del>
            {% endif %}
            <strong><span>#{{product.get_real_price}}</span></strong>

        </div>

        <div class="product_details">
            <h3>Product Details</h3>
            <hr>

            <p>{{product.description}}</p>

        </div>

        <div class="product_specification">
            <h3>Specifications</h3>

            <div class="key_features">
                <h4>Key Features</h4>

                <p>{{product.key_features}}</p>

            </div>

            <div class="specification">
                <h4>Specifications</h4>
<!--                <&#45;&#45; check for synonym&ndash;&gt;-->
                <p>{{product.specifications}}</p>
            </div>

        </div>

        <div class="customer_feedback">
            <div class="product_ratings">

            </div>

            <div class="comments">
                <h3>Comments From Verified Purchases ({{feedback.count}})</h3>
                {% for feed in feedback %}
                    <div class="individual_comment">
                        <span>{{feed.rating}}</span>
                        <strong><p>{{feed.topic}}</p></strong>
                        <p>{{feed.user.first_name}} {{feed.user.last_name}} {{feed.date_commented | timesince}}</p>
                    </div>
                {% endfor %}
            </div>

             <div class="seller_information">
                    <h5>Seller Information</h5>
                    <span>{{product.vendor.name_of_store}}</span>
             </div>


        </div>

    </div>

    <div class="product_sales_info">
        <table>
            <h2>Product Sales History</h2>
            <tr>
                <th>S/N</th>
                <th>Date</th>
                <th>Quantity</th>
                <th>Customer</th>
                <th>Price</th>
            </tr>

            {% for product in product_sales %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{product.date_checked_out}}</td>
                <td>{{product.quantity}}</td>
                <td>{{product.user.username}}</td>
                <td>{{product.individual_product_price}}</td>
            </tr>
            {% empty %}

            <tr><td colspan="3">No sales yet</td></tr>
            {% endfor %}


            <tr>
                <td colspan="2">Total Quantity Sold</td>
                <td>{{total_quantity}}</td>
            </tr>

            <tr>
                <td colspan="2">Total Amount generated</td>
                <td colspan="2">{{total_sold}}</td>
            </tr>

        </table>

    </div>


</div>
{% endblock %}