e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('NoBoneZ/', admin.site.urls),
    path("main_store/", include("main_store.urls")),
    path("", RedirectView.as_view(url="main_store/", permanent=True)),
    path("accounts/", include('nucleus.urls')),
    path("admin_overwatch/", include("admin_overwatch.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_store/urls.py
from django.urls import path

from . import views

app_name = "main_store"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/product_details/", views.product_details, name="product_details"),
    path("<int:pk>/product_details/make_report", views.make_report, name="make_report"),
    path("<int:pk>/add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("order_summary/", views.order_summary, name="order_summary"),
    path("<int:pk>/order_summary/<int:id>/remove_product", views.remove_from_cart, name="remove_from_cart"),
    path("<int:pk>/order_summary/<int:id>/reduce_quantity", views.reduce_quantity, name="reduce_quantity"),
    path("<int:pk>/order_summary/<int:id>/increase_quantity", views.increase_quantity, name="increase_quantity"),
    path("<int:pk>/save_product_wishlist/<int:id>", views.save_product, name="save_product"),
    path("<int:pk>/remove_product_wishlist/<int:id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("<int:pk>/check_out/", views.user_checkout, name="checkout"),

]

nucleus/urls.py
from django.urls import path

from . import views

app_name = "nucleus"

urlpatterns = [
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_in/", views.user_sign_in, name="sign_in"),
    path("sign_out/", views.user_sign_out, name="sign_out"),
    path("password_recovery/", views.recover_password, name="recover_password"),
    path("reset_password/password-token/<str:uid>/<str:token>", views.reset_password, name="reset_password"),

    path("profile/<int:pk>/", views.UserProfile.as_view(), name="profile"),
    path("profile/<int:pk>/update_details/", views.user_update_details, name="update_details"),
    path("profile/<int:pk>/change_password/", views.change_password, name="change_password"),
    path("profile/<int:pk>/close_account/", views.close_account, name="close_account"),
    path("profile/<int:pk>/wishlist/", views.user_wishlist, name="user_wishlist"),
    path("profile/<int:pk>/user_review/", views.user_review, name="user_review"),
    path("profile/<int:pk>/address_book/", views.UserAddress.as_view(), name="user_address"),
    path("profile/<int:pk>/inbox", views.UserInbox.as_view(), name="user_inbox"),
    path("profile/<int:pk>/my_orders", views.UserAllOrders.as_view(), name="user_all_orders"),
]

main_store/forms.py
from django import forms

from .models import Checkout, Report, Feedback


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Checkout
        exclude = ("user", "checkout_date",)


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        exclude = ("product",)


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ("user", "product", "date_commented", "is_active")

main_store/views.py
from math import fsum

from datetime import date, datetime
from random import shuffle, sample

from django.db.models import Q
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseForbidden
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, View
from django.contrib.sessions.backends.db import SessionStore

from .models import Category, Product, OrderedProduct, Cart, WishList, Checkout, Feedback
from .forms import CheckoutForm, ReportForm


# Create your views here.


def get_cart_total(pk):
    cart = Cart.active_objects.filter(user_id=pk).first()
    ordered_products = cart.ordered_products.all()
    prices = 0

    for product in ordered_products:
        prices += product.product.get_real_price() * product.quantity

    return prices


def index(request):
    sales = []
    hot_deals = []
    categories_for_recommendation = []
    recommended_products_list = []

    categories = Category.objects.all()

    search = request.GET.get("search") if request.GET.get("search") is not None else ""

    products = Product.active_objects.filter(
        Q(name__icontains=search) | Q(sub_category__category__name__icontains=search))

    all_settled_carts = Cart.inactive_objects.all()

    for cart in all_settled_carts:
        for goods in cart.ordered_products.all():
            sales.append(goods)

    hot_products = Product.active_objects.all()
    for selected_product in hot_products:
        if selected_product.get_price_discount_percentage() > 0:
            hot_deals.append(selected_product)

    try:
        wish_recommended_for_you = WishList.objects.get(user_id=request.user.id).saved_products.all()
        for recommended_goods in wish_recommended_for_you:
            categories_for_recommendation.append(recommended_goods.get_category())
    except:
        pass

    for merchandise in Product.objects.all():
        if merchandise.get_category() in categories_for_recommendation and merchandise not in wish_recommended_for_you:
            recommended_products_list.append(merchandise)

    context = {
        "categories": categories,
        "products": products,
        "sales": sales,
        "hot_deals": hot_deals[:5],
        "recommended_products": recommended_products_list[:5]
    }
    return render(request, "main_store/index.html", context)


def add_to_cart(request, pk):
    if request.user.is_authenticated:
        marked_product = Product.objects.get(id=pk)
        ordered_product, created = OrderedProduct.not_moved_objects.get_or_create(user=request.user,
                                                                                  product=marked_product)
        selected_cart = Cart.active_objects.filter(user=request.user).first()

        if selected_cart is not None:
            if ordered_product in selected_cart.ordered_products.all():
                ordered_product.quantity += 1
                ordered_product.save()
                messages.success(request, f'{ordered_product} added successfully')
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
            else:
                selected_cart.ordered_products.add(ordered_product)
                messages.success(request, f'{ordered_product} added successfully')
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        else:
            new_cart = Cart.objects.create(user=request.user, )
            new_cart.ordered_products.add(ordered_product)
            new_cart.save()
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    else:
        marked_product = Product.objects.get(id=pk)
        ordered_product, created = OrderedProduct.not_moved_objects.get_or_create(
            ip_address=request.META.get("REMOTE_ADDR"),
            product=marked_product
        )
        selected_cart = Cart.active_objects.filter(ip_address=request.META.get("REMOTE_ADDR")).first()

        if selected_cart is not None:
            if ordered_product in selected_cart.ordered_products.all():
                ordered_product.quantity += 1
                ordered_product.save()
                messages.success(request, f'{ordered_product} added successfully using address')
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
            else:
                selected_cart.ordered_products.add(ordered_product)
                messages.success(request, f'{ordered_product} added successfully using address')
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

        else:
            new_cart = Cart.objects.create(ip_address=request.META.get("REMOTE_ADDR"))
            new_cart.ordered_products.add(ordered_product)
            new_cart.save()
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="nucleus:sign_in")
def remove_from_cart(request, pk, id):
    if request.user.id != pk:
        return HttpResponseForbidden()

    selected_cart = Cart.active_objects.filter(user_id=pk).first()
    selected_product = OrderedProduct.not_moved_objects.filter(user_id=pk, product_id=id).first()

    selected_cart.ordered_products.remove(selected_product)
    selected_product.save()

    selected_product.quantity = 1
    selected_product.save()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="nucleus:sign_in")
def order_summary(request):
    # if request.user.id != pk:
    #     return HttpResponseForbidden()

    selected_cart = Cart.active_objects.filter(user_id=request.user.id).first()

    try:
        user_wishlist = WishList.objects.get(user_id=request.user.id)
        selected_wishlist = user_wishlist.saved_products.all()[:5]
    except:
        selected_wishlist = []

    if selected_cart is not None:
        ordered_products = selected_cart.ordered_products.all()

        context = {
            "ordered_products": ordered_products,
            "cart": selected_cart,
            "total": get_cart_total(request.user.id),
            "wishlist": selected_wishlist,
        }
        return render(request, "main_store/cart_summary.html", context)
    else:
        messages.error(request, "Cart is empty")
        return HttpResponseRedirect(reverse("main_store:index"))


@login_required(login_url="nucleus:sign_in")
def reduce_quantity(request, pk, id):
    if request.user.id != pk:
        return HttpResponseForbidden()

    selected_product = OrderedProduct.not_moved_objects.filter(user_id=pk, product_id=id).first()
    if selected_product.quantity > 1:
        selected_product.quantity -= 1
        selected_product.save()
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    messages.error(request, f"{selected_product} quantity can't go below 1, You could remove it instead ")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="nucleus:sign_in")
def increase_quantity(request, pk, id):
    if request.user.id != pk:
        return HttpResponseForbidden()

    selected_product = OrderedProduct.not_moved_objects.filter(user_id=pk, product_id=id).first()
    selected_product.quantity += 1
    selected_product.save()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="nucleus:sign_in")
def save_product(request, pk, id):
    user_wishlist, created = WishList.objects.get_or_create(user_id=pk)
    product = Product.objects.get(id=id)

    if product not in user_wishlist.saved_products.all():
        user_wishlist.saved_products.add(product)
        messages.error(request, f"{product.name} saved in wish list")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    user_wishlist.saved_products.remove(product)
    messages.error(request, f"{product.name} removed from wish list")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="nucleus:sign_in")
def user_checkout(request, pk):
    if request.user.id != pk:
        return HttpResponseForbidden()

    # TRY AND APPLY TIMEDELTA AMD TIMEZONE
    form = CheckoutForm()
    selected_cart = Cart.active_objects.filter(user_id=pk).first()
    products = selected_cart.ordered_products.all()
    total = get_cart_total(pk)
    page = "checkout_form"

    if len(products) == 0:
        messages.error(request, "Cart is empty")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    if request.method == "POST":
        form = CheckoutForm(request.POST, request.FILES)
        print(form.errors)

        if form.is_valid():
            checkout = form.save(commit=False)
            checkout.user = request.user
            checkout.save()

            selected_cart.is_checked_out = True
            selected_cart.date_checked_out = datetime.now()
            selected_cart.save()

            for product in products:
                product.is_checked_out = True
                product.date_checked_out = date.today()
                product.save()

            messages.success(request, "Your goods will be delivered to you within 3 working days")
            return HttpResponseRedirect(reverse("main_store:index"))

        messages.error(request, "kindly check the form, invalid details")

    context = {
        "form": form,
        "products": products,
        "total": total,
        "page": page,
    }
    return render(request, "main_store/store_forms.html", context)


@login_required(login_url="nucleus:sign_in")
def product_details(request, pk):
    rating_list = []
    product = Product.objects.get(id=pk)
    feedback = Feedback.objects.filter(product_id=pk)

    for rating in feedback:
        rating_list.append(int(rating.rating))

    try:
        average_rating = fsum(rating_list) / len(rating_list)
    except ZeroDivisionError:

templates/main_store/cart_summary.html
{% extends "base.html" %}
{% load static %}

{% block title %}<title>Cart Summary</title>{% endblock %}
{% block content %}
<style>

    .cart_summary{
        display: grid;
        grid-template-columns: 5fr 2fr;
        grid-template-rows: auto;
        column-gap: 30px;
    }

    .individual_ordered_product{
        border:1px solid ;
        border-radius:8px;
        margin:40px;
        padding:45px;
    }

    .individual_ordered_product h5{
        float:right;
        margin: 200px 0px 0px px;

    }

    .individual_ordered_product del{
        float:right;

    }



    .summary_product_picture {
        margin: -20px 5px 0px -10px;
        width:70px;
        height:70px;
        float:left;
    }

    .style_cart_summary{
        background-color:;
        margin: 50px 20px  10px 90px;

    }

    .quantity_control{
        float:right;
    }

    .quantity_control span{
        margin:0px 0px 0px -10px;
    }

    .summary_remove{
        float:left;
        width:20px;
        height:20px;

    }

    .summary_remove img{
        width:20px;
        height:20px;
        margin:0px -5px -22px -30px;

    }

    .summary_remove span{
        margin:0px 0px -10px -7px;

    }

    .summary_increase{
        margin:0px 0px -20px -30px;
    }

    .summary_increase img{
        width:20px;
        height:20px;
    }

    .summary_reduce{
        margin:-20px 0px 0px -0px;
    }

     .summary_reduce img{
        width:20px;
        height:20px;

    }

    .cart_summary_header h3{
        margin-top: 30px;
        margin-bottom: -20px;
        margin-left:250px;
        font-type:helvetica;
    }

    .cart_summary_header img{
        width:20px;
        height:20px;
        margin-left: 20px;
        margin-top : -900px;
     }

    .total_price{
        border-radius:5px;
        margin:20px;
        padding:10px;
    }

    .total_price button{
        display:block;
        margin-top:10px;
        cursor:pointer;
    }

    .about_returns{
        border-radius:5px;
        margin:20px;
        padding:10px;
    }

    .total_price_returns{
        position:sticky;
        top:0;
    }

    .all_products_in_wishlist{
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
        row-gap: 0px;
        column-gap: 10px;
        border-radius:6px;
        margin: 0px 520px 50px 120px;


  }

    .wishlist h3{
        margin-left:120px;
        font-size:20px;
    }

    .wishlist_products{
         margin:20px 0px 0px 0px;
        padding:20px;
        border:1px solid white;
        border-radius:10px;
        box-shadow: 3px 3px 3px 3px gainsboro;
    }


    .wishlist_products button{
        margin-top:50px;
        margin-left:20px;
        background-color:#FF9C6E;
        color:white;
        border:1px solid #FF9C6E;
        border-radius:5px;
        cursor:pointer;
        padding:5px;

    }

    .wishlist_discount{
        float:right;
        margin-top:-40px;
        margin-left: 20px;
    }

    .sum_wish_prod {
        width:50px;
        height:50px;
        float:left;

    }



</style>


<div class="cart_page">

    <div class="cart_summary">
        <div class="style_cart_summary">

                <div class="cart_summary_header">
                        <h3>{{cart.user.username | title}} <span><strong>, Here is your order summary</strong></span></h3>

                        <a href="{{request.META.HTTP_REFERER}}">
                            <img src="{% static 'images/arrow-left.svg' %}" alt="Go Back">
                        </a>
                </div>

            {% for product in ordered_products %}
            <div class="individual_ordered_product">
                <a href="{% url 'main_store:product_details' product.product.id %}">
                <img src="{{product.product.picture_of_product_1.url}}" alt="{{product.product.name}}" class="summary_product_picture">
                    <a/>
                <p class="summary_p_n"><strong>{{product.product.name}}</strong></p>

                {% if product.product.discount > 0 %}
                    <h5>--{{product.product.get_price_discount_percentage}}% off</h5>
                    <del>{{product.product.price}}</del>
                {% endif %}

                <p><strong>#{{product.product.get_real_price}}</strong></p>

                <h4>seller: {{product.product.vendor.name_of_store}}</h4>


                <div class="summary_remove">
                    <a href="{% url 'main_store:remove_from_cart' request.user.id product.product.id %}">
                        <img src="{% static 'images/trash.svg' %}" alt="Remove">
                        <span><strong>REMOVE</strong></span>
                    </a>
                </div>

                <div class="quantity_control">

                    <div class="summary_increase">
                        <a href="{% url 'main_store:increase_quantity' request.user.id product.product.id %}">
                        <img src="{% static 'images/arrow-up.svg' %}" alt="increase_quantity">
                        </a>
                    </div>

                    <span>{{product.quantity}}</span>

                    <div class="summary_reduce">
                        <a href="{% url 'main_store:reduce_quantity' request.user.id product.product.id %}">
                        <img src="{% static 'images/arrow-down.svg' %}" alt="reduce quantity">
                        </a>
                    </div>

                </div>

            </div>


            {% empty %}
            <p>No products in the Cart. To add products to the Cart, kindly browse our <a href="{% url 'main_store:index' %}">Categories</a></p>
            {% endfor %}
        </div>


        {% if ordered_products.count > 0 %}
            <div class="total_price_returns">
                <div class="total_price">
                    <p><strong>SUBTOTAL : </strong></p>
                    <span>#{{total}}</span>

                    <p ><small>Delivery fees not included yet</small></p>
                    <a href="{% url 'main_store:checkout' request.user.id %}"><button type="submit">CHECKOUT</button></a>
                </div>

                <div class="about_returns">
                    <h5>Returns are easy</h5>
                    <p>Free return within 15 days for Official Store products and 7 days for products from other vendors.</p>
                </div>

            </div>
        {% endif %}


    </div>


    <br>
    <br>
    <br>
    <div class="wishlist">
        <h3>Wishlist</h3>

        <div class="all_products_in_wishlist">
            {% for product in wishlist %}
            <div class="wishlist_products">
                <img src="{{product.picture_of_product_1.url}}" alt="{{product.name}}" class="sum_wish_prod">
                <p>{{product.name}}</p>
                <p><strong>#{{product.get_real_price}}</strong></p>


                 <a href="{% url 'main_store:add_to_cart' product.id %}">
                     <button type="submit"> ADD TO CART</button>
                 </a>
            </div>
            {% empty %}
                <p>No products in your wishlist</p>
            {% endfor %}
        </div>
    </div>





</div>
{% endblock %}

templates/main_store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>{{product.name | title}}</title>{% endblock %}
{% block content %}
<style>
    .whole_product_details_page{
        display:grid;
        grid-template-columns:3fr 1fr;
        color:black;
    }

    .mainly_product_details{
         margin-left:150px;
         margin-right:50px;

    }

    .intro_details{
         margin:50px 50px 10px 150px;


    }

    .intro_details h3{
         margin:-120px 380px 10px 180px;
         padding:5px

    }

    .intro_details img{
         width:150px;
         height:150px;
         margin-left :10px;

    }

    .intro_details del{
         margin-left:20px;

    }

    .real_price{
        margin:100px 0px 10px 10px;
        font-size:30px;
        font-weight:bold;

    }

    .discount{
        margin:0px 50px 90px 200px;
        font-size:15px;

    }


     .product_details{
         margin:40px 50px 10px 150px;

    }

     .product_specification{
         margin:40px 50px 40px 150px;
         display:grid;
         grid-template-columns:1fr 1fr;
         column-gap:20px;

    }

     .customer_feedback{
         margin:50px 50px 50px 150px;
         display:grid;
         grid-template-columns: 1fr 2fr;
         column-gap:200px;

    }

    .product_detail_add_to_cart{
        margin:0px 50px 0px 200px;
        cursor:pointer;
    }

    .product_detail_add_to_cart button{
        margin:0px 50px 0px 200px;
        cursor:pointer;
        background-color:#FF9C6E;
        color:white;
        border:1px solid #FF9C6E;
        border-radius:5px;
        cursor:pointer;
        padding:10px;
    }

    .product_detail_add_to_wishlist img{
        width:30px;
        height:30px;
        float:right;
        margin:-235px 15px 0px 0px;
    }

     .rvp_like_product{
        width:30px;
        margin:0px 0px -25px 60px;
     }



     .rvp{
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
        column-gap:15px;
     }


     .recently_viewed_products{
        margin-left:150px;
        margin-right:50px;
        margin-bottom: 10px;
     }

     .recently_viewed_products h3{
        text-decoration:underline;
     }

    .rvp p{
        margin-bottom: 10px;
     }

     .rvp_cart_logo img{
        float:right;
        width:30px;
        margin: 0px 0px -5px 100px
     }

     .individual_rvp{
        margin:15px 0px;
        padding:10px;
        border:1px solid white;
        border-radius:10px;
        box-shadow: 3px 3px 3px 3px gainsboro;
     }

     .rvp_discount{
     }

     .rvp_discount h5{
        float:right;
        margin:-125px 0px 0px 90px;

     }

     .rvp_discount h4{
        float:right;
        margin: -90px -10px 0px -15px;
        padding-left: px;
     }



     .rvp_product_picture{
        width:70px;
        height:70px;
        margin-bottom: 15px;

     }



     .rvp_like_product img{
        float:left;
        width:20px;
        margin:5px 0px -5px -50px;
     }

     .key_features h4{
        text-decoration:underline;
     }

     .specification h4{
        text-decoration:underline;
     }

    .test_rvp{
        margin:5px;
    }

    .seller_information{
        padding:10px;
        border-radius:8px;
        margin:20px 20px 0px 10px;

    }

    .seller_information button{
        display:block;
        margin-top:10px;

    }

    .average_rating{
        margin:20px 0px;
    }

    .product_image {
        border:4px solid white;
        border-radius:10px;
        box-shadow: 2px 2px 2px 3px gainsboro;
    }






</style>



<div class="whole_product_details_page">
    <div class="mainly_product_details">
        <div class="intro_details">

            <div >
                <img src="{{product.picture_of_product_1.url}}" alt="{{product.name}}" class="product_image">
                <h3>{{product.name}}</h3>

                {% if product.discount > 1%}
                    <span class="discount">-{{product.get_price_discount_percentage}}% off</span>
                    <p class="real_price">#{{product.get_real_price}}</p>
                    <del>#{{product.price}}</del>
                {% else %}
                    <p class="real_price">#{{product.get_real_price}}</p>
                {% endif %}


                <div class="product_detail_add_to_cart">
                    <a href="{% url 'main_store:add_to_cart' product.id %}">
                        <button type="submit">ADD TO CART</button>
                    </a>
                </div>

                <div class="product_detail_add_to_wishlist">
                    <a href="{% url 'main_store:save_product' request.user.id product.id %}">
                        <img src="{% static 'images/heart.svg' %}" alt="add_to_wishlist">
                    </a>
                </div>



                <a href="{% url 'main_store:make_report' product.id %}">Report Incorrect Product Information</a>
            </div>

        </div>

        <div class="product_details">
            <h3>Product Details</h3>
            <hr>

            <p>{{product.description}}</p>

        </div>

        <div class="product_specification">

            <div class="key_features">
                <h4>Key Features</h4>

                {% if product.key_features %}
                    <p>{{product.key_features}}</p>
                {% else %}
                    <p>No Key Features Available</p>
                {% endif %}

            </div>

            <div class="specification">
                <h4>Specifications</h4>
                {% if product.specifications %}
                    <p>{{product.specifications}}</p>
                {% else %}
                    <p>No Specifications Available.</p>
                {% endif %}
            </div>

        </div>

        <div class="customer_feedback">
            <div class="product_ratings">
                <h2>Product Rating Summary</h2>

                {% if rating %}
                    <h4 class="average_rating">Average Rating</h4>
                    <h4>{{rating}} / 5</h4>
                {% else %}
                    <p>No Ratings Yet</p>
                {% endif %}

            </div>

            <div class="comments">
                <h3>Comments From Verified Purchases ({{feedback.count}})</h3>
                {% for feed in feedback %}
                    <div class="individual_comment">
                        <span>{{feed.rating}}/5</span>
                        <strong><p>{{feed.topic}}</p></strong>
                        <br>
                        <p>{{feed.comments}}</p>
                        <br>
                        <p>{{feed.user.username | title}}  {{feed.date_commented | timesince}} ago</p>
                        <hr>
                    </div>
                {% empty %}
                <p>No Comments Yet</p>
                {% endfor %}
            </div>

        </div>


        {% if request.user.is_authenticated %}
            <div class="recently_viewed_products">
                <h3>Recently Viewed Products</h3>

                <div class="rvp">
                {% for rvp in recently_viewed_products %}
                <div class="individual_rvp">
                    <div class="test_rvp">
                        <a href="{% url 'main_store:product_details' rvp.id%}">
                            <img src="{{rvp.picture_of_product_1.url}}" alt="{{rvp.name}}" class="rvp_product_picture">
                        </a>

                        <p>{{rvp.name}}</p>


                        <div class="rvp_discount">
                            {% if rvp.discount > 1 %}
                            <h4><del>#{{rvp.price}}</del></h4>
                            <h5>-{{rvp.get_price_discount_percentage}}%</h5>
                            {% endif %}
                        </div>

                        <p>#{{rvp.get_real_price}}</p>

                            <div class="rvp_like_product">
                                <a href="{% url 'main_store:save_product' request.user.id rvp.id %}"><img src="{% static 'images/heart.svg' %}" alt="like_product" class=""></a>
                            </div>

                        <div class="rvp_cart_logo">
                            <a href="{% url 'main_store:add_to_cart' rvp.id %}"><img src="{% static 'images/add-to-cart.png' %}" alt="add_to_cart" class=""></a>
                        </div>
                    </div>

                </div>
                {% empty %}
                <p>No item viewed yet</p>
                {% endfor %}
             </div>
            </div>
        {% endif %}
    </div>

    <div class="extra_info">
        <div class="seller_information">
            <h5>Seller Information</h5>
                <span>{{product.vendor.name_of_store}}</span>
                <span><strong>Followers: </strong>{{product.vendor.followers.count}}</span>
                <a href="">
                    <button type="button">Follow</button>
                </a>


        </div>

    </div>


</div>
{% endblock %}