e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('NoBoneZ/', admin.site.urls),
    path("main_store/", include("main_store.urls")),
    path("", RedirectView.as_view(url="main_store/", permanent=True)),
    path("accounts/", include('nucleus.urls')),
    path("admin_overwatch/", include("admin_overwatch.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_store/urls.py
from django.urls import path

from . import views

app_name = "main_store"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/product_details/", views.product_details, name="product_details"),
    path("<int:pk>/product_details/make_report", views.make_report, name="make_report"),
    path("<int:pk>/add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("order_summary/", views.order_summary, name="order_summary"),
    path("<int:pk>/order_summary/<int:id>/remove_product", views.remove_from_cart, name="remove_from_cart"),
    path("<int:pk>/order_summary/<int:id>/reduce_quantity", views.reduce_quantity, name="reduce_quantity"),
    path("<int:pk>/order_summary/<int:id>/increase_quantity", views.increase_quantity, name="increase_quantity"),
    path("<int:pk>/save_product_wishlist/<int:id>", views.save_product, name="save_product"),
    path("<int:pk>/remove_product_wishlist/<int:id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("<int:pk>/check_out/", views.user_checkout, name="checkout"),

]

nucleus/urls.py
from django.urls import path

from . import views

app_name = "nucleus"

urlpatterns = [
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_in/", views.user_sign_in, name="sign_in"),
    path("sign_out/", views.user_sign_out, name="sign_out"),
    path("password_recovery/", views.recover_password, name="recover_password"),
    path("reset_password/password-token/<str:uid>/<str:token>", views.reset_password, name="reset_password"),

    path("profile/<int:pk>/", views.UserProfile.as_view(), name="profile"),
    path("profile/<int:pk>/update_details/", views.user_update_details, name="update_details"),
    path("profile/<int:pk>/change_password/", views.change_password, name="change_password"),
    path("profile/<int:pk>/close_account/", views.close_account, name="close_account"),
    path("profile/<int:pk>/wishlist/", views.user_wishlist, name="user_wishlist"),
    path("profile/<int:pk>/user_review/", views.user_review, name="user_review"),
    path("profile/<int:pk>/address_book/", views.UserAddress.as_view(), name="user_address"),
    path("profile/<int:pk>/inbox", views.UserInbox.as_view(), name="user_inbox"),
    path("profile/<int:pk>/my_orders", views.UserAllOrders.as_view(), name="user_all_orders"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Title</title>{% endblock %}
</head>
<body>
    {% include "navbar.html" %}

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}
    {% endblock %}

    {% include "footer.html" %}
</body>
</html>

templates/footer.html
{% load static %}

<style>

    .t_footer{
        position:relative;
        margin-top:auto;
        background-color:grey;
    }

    .footer{
        display:grid;
        grid-template-rows:2fr 1fr 1fr;
        position:sticky;
        bottom:0;
        background-color:;
        margin:auto;
    }

    .footer_top{
        display:grid;
        grid-template-columns:1fr 3fr 1fr;
        background-color:#212143;

    }
     .f_logo_text{
        margin-top: 20px;
        font-size: 30px;
        font-family: 'Brush Script MT', cursive;
        color:white;
    }

    .f_logo{
        margin-top:10px;
        filter: invert(100%)
    }

    .footer_searchbar{
        margin-left:250px;
        margin-top: 30px;
        margin-bottom:10px;
        color:white;
        border-radius:5px;

    }

    .footer_searchbar input[type=text]{
       padding-left:10px;
       height:35px;


    }

    .footer_searchbar h3{
        margin-bottom:20px;
    }

    .footer_app h3{
        margin-bottom:20px;
    }

    .footer_app{
        color:white;
    }


     .footer_searchbar p{
        margin-bottom:10px;
    }

    .footer_searchbar button{
        background-color:black;
        color:white;
        border:1px solid white;
        padding:5px 10px;
        margin-right:10px;
        cursor:pointer;
        margin-left :5px;
        border-radius:5px;
    }


    .f_searchbar {
        margin-bottom:10px;
        width:400px;
        height:40px;
        border-radius:8px;
    }

    .f_searchbar {
        margin-bottom:10px;
        width:400px;
        height:40px;
        border-radius:8px;
    }

    .footer_mid_2{
        display:flex;
        align-items:center;
        justify-content:center;
        background-color:#21214B;

    }

    .footer_mid_2 p{
       font-size:25px;
       color:white;
    }

    .footer_mid_2 p{
        font-family: 'Brush Script MT', cursive;

    }


    .footer_bottom{
        background-color:#21214B;
    }

    .footer_bottom img{
        max-width:20px;
        margin: 0 10px;
        filter:invert(100%);
    }

    .footer_bottom p{
        font-size:20px;
        text-align:center;
        color:white;
    }

    .footer_bottom li{
        display:inline;
        list-style-type:none;
        align-items:center;
    }

    .footer_bottom a{
        text-decoration:none;
    }

    .footer_app{
        margin-top:30px;
    }

    .footer_app img{
        max-width:30px;
        margin:5px 15px 0 0;
        filter: invert(100%);
    }

    .social_media_links{
        margin:10px 0px 0px 550px;
    }

    .sub_new{
        margin-top:-10px;
    }

    .access_offer{
        margin-top:-10px;
    }

</style>
<div class="t_footer">
    <div class="footer">
            <div class="footer_top">

                <div class="footer_logo">
                     <a class="logo" href="{% url 'main_store:index' %}">
                        <img src="{% static 'images/vilgax.png' %}" alt="My_logo" class="f_logo" >
                        <p class="f_logo_text">Vilgax Stores</p>
                     </a>
                </div>

                <div class="footer_searchbar">
                    <h3><strong>New to Vilgax Stores ?</strong> </h3>
                    <p class="sub_new">Subscribe to our newsletter to get updates on our latest offers!</p>
                    <input type="text" value="{{request.user.email}}" class="f_searchbar">
                    <button>MALE</button>
                    <button>FEMALE</button>

                </div>

                <div class="footer_app">
                    <h3><strong>Download Free Vilgax App</strong> </h3>
                    <p class="access_offer">Get access to exclusive offers!</p>

                    <a href="">
                        <img src="{% static 'images/apple-brands.svg' %}" alt="Apple" width="30px">
                    </a>

                    <a href="">
                    <img src="{% static 'images/google-play-brands.svg' %}" alt="Google" width="30px">
                    </a>

                </div>

            </div>


            <div class="footer_mid_2">
                <p>Developed By Koder Blvck(47)</p>

            </div>

            <div class="footer_bottom">
                <p>Contact him on</p>

                <ul>

                    <div class="social_media_links">
                        <li>
                            <a href="https://twitter.com/koder_black" target="_blank">
                                <img src="{% static 'images/twitter-brands.svg' %}" alt="Twitter">
                            </a>
                        </li>

                        <li>
                            <a href="https://www.linkedin.com/mwlite/in/abraham-adekunle-35269422b" target="_blank">
                                <img src="{% static 'images/linkedin-in-brands.svg' %}" alt="LinkedIn">
                            </a>
                        </li>

                        <li>
                            <a href="https://www.facebook.com/ab.graham1/" target="_blank">
                                <img src="{% static 'images/facebook-brands.svg' %}" alt="Facebook">
                            </a>
                        </li>

                        <li>
                            <a href="https://wa.link/i7ffjk" target="_blank">
                                <img src="{% static 'images/whatsapp-brands.svg' %}" alt="Whatsapp">
                            </a>
                        </li>

                        <li>
                            <a href="" target="_blank">
                                <img src="{% static 'images/instagram-brands.svg' %}" alt="Instagram">
                            </a>
                        </li>

                        <li>
                            <a href="https://t.me/KoderBlvck" target="_blank">
                                <img src="{% static 'images/telegram-brands.svg' %}" alt="Telegram">
                            </a>
                        </li>


                        <li>
                            <a href="https://github.com/NoBoneZ" target="_blank">
                                <img src="{% static 'images/github-brands.svg' %}" alt="Github">
                            </a>
                        </li>

                        <li>
                            <a href="mailto:adekunleabraham09@gmail.com" target="_blank">
                                <img  src="{% static 'images/envelope-solid.svg' %}" alt="Gmail">
                            </a>
                        </li>
                    </div>


                </ul>

            </div>

    </div>
</div>

templates/navbar.html
{% load static %}

<style>
    *{
        margin: 0;
        box-sizing: border-box;
    }


    .nav_bar{
        display: flex;
        justify-content: space-between;
        padding: 2px;
        background-color: ghostwhite;
        position: sticky;
        top: 0;
    }

    .logo{
        display: flex;
        justify-content: space-evenly;
        text-decoration:none;
        color:black;
    }

    .logo img{
        width: 70px;
        height: 70px;
    }

    .logo_text{
        margin-top: 20px;
        font-size: 20px;
        font-family: 'Brush Script MT', cursive;
    }

    .main_search_bar{
        width: 300px;
        height: 40px;
        border:1px solid #1D39C4;
        border-radius:10px;
        margin-left:-100px;
        margin-top:20px;
        padding:10px;
    }


    .login{
        width:40px;
        margin-left:-50px;
        margin-top:10px;
    }

    .cart{
        width:30px;
        margin-top:10px;
        margin-left:-50px;
    }

    .profile{
        width:30px;
        margin-top:10px;
        margin-left:-50px;
    }

    .logout{
        width:30px;
        margin-top:10px;
        margin-left:90px;
    }

    .cart_total{
        border:1px solid black;
        padding:5px;
        border-radius:400000px;
        text-decoration:none;
        color:white;
        background-color:black;

    }


</style>

<div class="nav_bar">

    <a class="logo" href="{% url 'main_store:index' %}">
        <img src="{% static 'images/vilgax.png' %}" alt="My_logo" class="logo" >
        <p class="logo_text">Vilgax Stores</p>
    </a>

    <form>
    <input class="main_search_bar" type="text" name="search" placeholder="Enter Product name, vendor, category">
    </form>


    {% if request.user.is_authenticated %}
        <a class="logout" href="{% url 'nucleus:sign_out' %}">
            <img src="{% static 'images/switch.png' %}"alt="My_logo" class="logout">
        </a>

          <a class="profile" href="{% url 'nucleus:profile' request.user.id %}">
            <img src="{% static 'images/user-interface.png' %}"alt="My_logo" class="profile">
        </a>
    {% else%}
         <a class="login" href="{% url 'nucleus:sign_in' %}">
            <img src="{% static 'images/enter.png' %}"alt="My_logo" class="login">
        </a>

    {% endif %}


         <a class="cart" href="{% url 'main_store:order_summary' %}">
                <img src="{% static 'images/shopping-cart.png' %}"alt="My_logo" class="cart">
                <sub class="cart_total">{{cart_total}}</sub>
            </a>
</div>